### ISSUE TITLE
Bug: 项目无法克隆

### ISSUE THREAD

**Issue by Sean1514** [imcuttle/mometa#12]
无法下载项目

**Comment by imcuttle** [comment]
@Sean1514  建议直接使用 git clone，不是 github 下载能力。猜想可能是截图比较多，导致仓库比较大

**Comment by Sean1514** [comment]
> 

应该是网络问题 早上不成功 显示超时 现在可以了

**Comment by imcuttle** [comment]
@Sean1514 请问 pnpm / node  版本是多少呢

**Comment by imcuttle** [comment]
@Sean1514  可能 pnpm 对于 windows 系统支持不全面，可以尝试使用类 linux shell，如 git shell / powershell；
或者换成 npm，但是换成 npm 安装，需要执行 `npx lerna bootstrap`，同时去掉 `preinstall` 禁止的钩子；

就算能够跑起来，可能 mometa 本身对于 windows 支持也比较有限，所以推进还是换成 类 linux shell，或者 mac 电脑 😢

**Comment by Sean1514** [comment]
> @Sean1514 可能 pnpm 对于 windows 系统支持不全面，可以尝试使用类 linux shell，如 git shell / powershell； 或者换成 npm，但是换成 npm 安装，需要执行 `npx lerna bootstrap`，同时去掉 `preinstall` 禁止的钩子；
> 
> 就算能够跑起来，可能 mometa 本身对于 windows 支持也比较有限，所以推进还是换成 类 linux shell，或者 mac 电脑 😢

好的 感谢解答

**Comment by imcuttle** [comment]
Duplicate of #20
