### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by free-qiaochen** [imcuttle/mometa#14]
**Describe the bug**
按照快速开始：
```
git clone https://github.com/imcuttle/mometa.git
cd mometa
pnpm install
cd packages/app && pnpm start
```
无法启动，
没有反应；
浏览器打开localhost:4000后一直白屏加载中,控制台也没有任何消息；
![image](https://user-images.githubusercontent.com/24800988/149473343-76f53f67-0f36-4801-b7d7-71e30bb65270.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - mometa version: 

**Additional context**

**Comment by imcuttle** [comment]
请带上 Node.js 版本/ NPM 版本 / PNPM 版本  @free-qiaochen

**Comment by imcuttle** [comment]
长时间没有回复，暂时关闭

**Comment by free-qiaochen** [comment]
环境信息：
node：v12.18.1
npm: 6.14.5
pnpm :6.24.3
macOS:10.15.6

**Comment by imcuttle** [comment]
@free-qiaochen  该问题已经修复，需要 node>=12.20 版本
