### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by 17biubiu** [imcuttle/mometa#18]
启动之后http://localhost:4000/
一直在加载，无任何显示
![image](https://user-images.githubusercontent.com/13295895/150061333-74b28531-5e51-471f-a871-c8f700cc80c1.png)

**Comment by imcuttle** [comment]
@17biubiu 带上 node.js pnpm npm os 信息

**Comment by 17biubiu** [comment]
@imcuttle 
node: v12.19.0
npm: 6.14.8
pnpm: 6.15.1
os: macos catalina 10.15.7

**Comment by 17biubiu** [comment]
本地执行的：pnpm run start:app:cr

**Comment by imcuttle** [comment]
@17biubiu 尝试升级 node 至14版本看看

**Comment by 17biubiu** [comment]
还是不行。终端直接打开地址是localhost:4000
![image](https://user-images.githubusercontent.com/13295895/150091611-dd29fee6-1d8f-4f37-8842-23265e980726.png)

**Comment by imcuttle** [comment]
@17biubiu  我使用 node: v12.19.0 复现了该问题，但是升级到  node: v12.20.0 或以上  就没有问题了，确认一下是否node已经升级

**Comment by 17biubiu** [comment]
ok了

**Comment by HuBoZhi** [comment]
node 为14.9.0 也不好使，将node版本降至v12.20.0之后好使了
