### ISSUE TITLE
Bug: 只能在本地run吗？

### ISSUE THREAD

**Issue by dwqs** [imcuttle/mometa#19]
> 由于 mometa 依赖本地开发环境，只使用在本地开发环境，所以没有搭建在线 demo

所以 mometa 是不支持在线部署，是吗？

**Comment by imcuttle** [comment]
@dwqs 

mometa 不是传统主流的低代码平台（如 amis/云凤蝶），mometa 是面向研发的、代码可视设计编辑平台；它更像是 dreamweaver、gui 可视编辑 之于 程序员。

所以它更像是辅助编码工具，而不是 No-Code (amis/云凤蝶)的平台方案；所以不建议在远端服务起一个本地开发环境，所以没有做在线部署。目前依赖 `webpack` dev 开发模式

但强行做在线部署也是可以的，只不过会存在多人同时修改同一份代码的一致性等问题

**Comment by imcuttle** [comment]
定位更多是 基于程序员本地开发的模式，新增了可视化编码的能力（修改的也是本地的代码文件本身）
