### ISSUE TITLE
Bug: puppeteer安装失败

### ISSUE THREAD

**Issue by yinxxy** [imcuttle/mometa#24]
![QQ截图20220121103957](https://user-images.githubusercontent.com/88623174/150456511-16283bb2-c8f5-4414-970a-1150534edf9c.png)
![111](https://user-images.githubusercontent.com/88623174/150456575-afdcb7d4-afea-48c4-a7e8-0ca9f24db94e.png)

**Comment by cklx0719** [comment]
一模一样的错误。。。+1
我在本地和一台服务器上都试了，一样的错误。
node   16.13.1
npm     8.3.2
pnpm   6.27.2

都是全新环境

**Comment by imcuttle** [comment]
@cklx0719 @yinxxy  你们都是window 系统吗

**Comment by imcuttle** [comment]
你们重新pull一下后试试

**Comment by 819295524** [comment]
我也一样下不了

**Comment by imcuttle** [comment]
请带上一下os版本信息

**Comment by gongzhaohui** [comment]
似乎package.json的scripts段，执行node脚本是有些地方漏掉了 “node ”。如"packlimit": "../../scripts/run packlimit" 可以改为"packlimit": "node ../../scripts/run packlimit"。设置环境变量，如"test": "NODE_OPTIONS=--experimental-vm-modules node ../../scripts/run test",也应改为"test": "set NODE_OPTIONS=--experimental-vm-modules && node ../../scripts/run test"。
我因为环境变量，也没有安装成功。

**Comment by cklx0719** [comment]
我本地是WIN11，服务器是ubuntu 20

**Comment by imcuttle** [comment]
> 似乎package.json的scripts段，执行node脚本是有些地方漏掉了 “node ”。如"packlimit": "../../scripts/run packlimit" 可以改为"packlimit": "node ../../scripts/run packlimit"。设置环境变量，如"test": "NODE_OPTIONS=--experimental-vm-modules node ../../scripts/run test",也应改为"test": "set NODE_OPTIONS=--experimental-vm-modules && node ../../scripts/run test"。 我因为环境变量，也没有安装成功。

@gongzhaohui  window batch cli 是不支持的，可以使用 linux shell，powershell 来执行
