### ISSUE TITLE
Bug: 项目启动时报错

### ISSUE THREAD

**Issue by studyand12** [imcuttle/mometa#25]
![2022-01-22(1).png](https://s2.loli.net/2022/01/22/pFD3t9lMrZOxzaW.png)
QAQ

**Comment by imcuttle** [comment]
是按照快速开始操作的吗

**Comment by studyand12** [comment]
是的，node啥的都是新装的.

**Comment by studyand12** [comment]
@imcuttle 对，之前的步骤都没报错。

**Comment by imcuttle** [comment]
@studyand12   看报错是直接执行的 `npm start`，antd 没有找到

**Comment by studyand12** [comment]
![2022-01-22 _1__1_.png](https://s2.loli.net/2022/01/22/IfxZ2tPiOlaJ7ed.png)
整体是这个样子 @imcuttle

**Comment by studyand12** [comment]
QAQ,我太笨了node啥的一点不会

**Comment by imcuttle** [comment]
@studyand12 你这代码看着不是最新代码
