### ISSUE TITLE
Bug: 请问不能使用window运行吗？

### ISSUE THREAD

**Issue by guanleming** [imcuttle/mometa#31]
警告: PowerShell 检测到你可能正在使用屏幕阅读器，并且已出于兼容性目的禁用 PSReadLine。如果要重新启用它，请运行 "Import-Module PSReadLine"。

PS C:\Users\v.guanym\Desktop> git clone https://github.com/imcuttle/mometa.git
Cloning into 'mometa'...
remote: Enumerating objects: 4233, done.
remote: Counting objects: 100% (3535/3535), done.
remote: Compressing objects: 100% (2155/2155), done.
remote: Total 4233 (delta 2341), reused 2363 (delta 1217), pack-reused 698Receiving objects: 100% (4233/4233), 11.03 MiBReceiving objects: 100% (4233/4233), 11.33 MiB | 946.00 KiB/s, done.

Resolving deltas: 100% (2624/2624), done.
PS C:\Users\v.guanym\Desktop> cd mometa
PS C:\Users\v.guanym\Desktop\mometa> pnpm install
Scope: all 10 workspace projects
Lockfile is up-to-date, resolution step is skipped
Packages: +3050
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\v.guanym\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 3050, reused 2895, downloaded 0, added 3050, done
node_modules/.pnpm/core-js@3.20.2/node_modules/core-js: Running postinstall script, done in 152ms
node_modules/.pnpm/core-js-pure@3.20.2/node_modules/core-js-pure: Running postinstall script, done in 154ms
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 184ms
node_modules/.pnpm/ejs@2.7.4/node_modules/ejs: Running postinstall script, done in 164ms
node_modules/.pnpm/@moyuyc+husky@1.1.1/node_modules/@moyuyc/husky: Running install script, done in 451ms
node_modules/.pnpm/highlight.js@9.18.5/node_modules/highlight.js: Running postinstall script, done in 132ms
node_modules/.pnpm/husky@4.3.8/node_modules/husky: Running install script, done in 559ms
node_modules/.pnpm/husky@4.3.8/node_modules/husky: Running postinstall script, done in 109ms
node_modules/.pnpm/edam-cli@3.4.15/node_modules/edam-cli: Running postinstall script, done in 88ms
 WARN  Failed to create bin at C:\Users\v.guanym\Desktop\mometa\node_modules\.bin\webpack. The source file at C:\Users\v.guanym\Desktop\mometa\node_modules\webpack\bin\webpack.js does not exist.
 EPERM  EPERM: operation not permitted, open 'C:\Users\v.guanym\Desktop\mometa\node_modules\.bin\webpack.CMD'

PS C:\Users\v.guanym\Desktop\mometa> pnpm run start:app:cr # 开启本地开发预览模式

> mometa@1.0.0 start:app:cr C:\Users\v.guanym\Desktop\mometa
> pnpm run start:cr --filter=@mometa/app

> @mometa/app@0.0.27 start:cr C:\Users\v.guanym\Desktop\mometa\packages\app
> NODE_OPTIONS="$INNER_NODE_OPTIONS" CLIENT_RENDER=1 node scripts/start.js

'NODE_OPTIONS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
C:\Users\v.guanym\Desktop\mometa\packages\app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @mometa/app@0.0.27 start:cr: `NODE_OPTIONS="$INNER_NODE_OPTIONS" CLIENT_RENDER=1 node scripts/start.js`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
PS C:\Users\v.guanym\Desktop\mometa>

**Comment by imcuttle** [comment]
可以使用 类 linux shell，本人没有windkw 电脑  不保证能在windows 跑起
