### ISSUE TITLE
npm i @mometa/editor -D 安装失败

### ISSUE THREAD

**Issue by qw1324** [imcuttle/mometa#32]
npm ERR! Invalid package name "JSONStream@1.3.5_8edd2f20adaf625cda7262506d877aea": name can only contain URL-friendly characters
[2022-01-25T23_01_44_431Z-debug.log](https://github.com/imcuttle/mometa/files/7937809/2022-01-25T23_01_44_431Z-debug.log)

**Comment by imcuttle** [comment]
带上环境信息

**Comment by qw1324** [comment]
> 带上环境信息

环境信息可以在哪看

**Comment by imcuttle** [comment]
> > 带上环境信息
> 
> 环境信息可以在哪看

系统信息  node版本  npm版本等

**Comment by qw1324** [comment]
npm: '7.20.5'
node: '16.13.2'

**Comment by imcuttle** [comment]
window 系统暂时不确定支持
