### ISSUE TITLE
Feature: 能否提供docker部署支持?

### ISSUE THREAD

**Issue by banduoba** [imcuttle/mometa#35]
可以提供基于docker部署的支持么

**Comment by imcuttle** [comment]
引自Readme：
> mometa 定位更多是 基于程序员本地开发的模式，新增了可视化编码的能力（修改的也是本地的代码文件本身）;
它更像是辅助编码工具，而不是 No-Code (amis/云凤蝶) 的平台方案；
不建议在远端服务起一个本地开发环境，所以没有做在线部署。
目前的实现依赖 webpack dev 开发模式，后续会考虑兼容 vite。

所以不适合做 docker 部署

**Comment by banduoba** [comment]
明白了 谢谢
