### ISSUE TITLE
Bug: Centos快速开始报错： Cannot find module 'xxx/mometa/packages/editor/node_modules/@mometa/fs-handler/lib'

### ISSUE THREAD

**Issue by ZhangJiaLei123** [imcuttle/mometa#36]
> 和已经提交的bug不一样 
## 环境版本： 
[root@localhost editor]# node -v
v16.13.2
[root@localhost editor]# npm -v

6.14.11
[root@localhost editor]# pnpm -v
6.28.0
## 错误信息 
![微信截图_20220129145038](https://user-images.githubusercontent.com/40969169/151665466-819e17ba-949f-4056-8680-46143bf5b932.png)

## 尝试过的解决方法 
* npm install @mometa/fs-handler
* pnpm install @mometa/fs-handler
![微信截图_20220129225300](https://user-images.githubusercontent.com/40969169/151665634-1f4302db-e273-4032-bb92-89c1ee642714.png)

![微信截图_20220129225358](https://user-images.githubusercontent.com/40969169/151665636-54e2bc64-c9a9-48ba-b287-0d663c766ba9.png)

**Comment by imcuttle** [comment]
fs-handler 是monorep 子包，可以进入到 fs-handler 目录，执行 build script

**Comment by ZhangJiaLei123** [comment]
请问是在packages/fs-handler 下执行 npm run吗？npm build都执行了，还是不行
```
[root@localhost mometa]# cd packages/fs-handler/
[root@localhost fs-handler]# build script
bash: build: command not found...

[root@localhost fs-handler]# npm build script
Unknown command: "build"

Did you mean this?
    npm run build # run the "build" package script

To see a list of supported npm commands, run:
  npm help
[root@localhost fs-handler]# npm script
Unknown command: "script"

To see a list of supported npm commands, run:
  npm help

[root@localhost fs-handler]# npm run
Lifecycle scripts included in @mometa/fs-handler@0.0.27:
  test
    ../../scripts/run test
  version
    npm test && npm run packlimit

available via `npm run-script`:
  build
    ../../scripts/run build
  packlimit
    ../../scripts/run packlimit
  dev
    npm run build -- --watch
  prepare
    npm run build
  prepublishOnly
    npm run packlimit
``
