### ISSUE TITLE
Bug: package.json  script start:app:cr 命令 在mac terminal下无法启动 需要把--filter前置

### ISSUE THREAD

**Issue by yxq2233234** [imcuttle/mometa#41]
按照readme直接pnpm  start:app:cr 启动，提示找不到命令。

应该是mac terminal对--filter的解析未生效。

建议将所有
```
"start:app:cr": "pnpm run start:cr --filter=@mometa/app",
```
改为
```
"start:app:cr": "pnpm --filter=@mometa/app run start:cr",
```

**Comment by liujiangde** [comment]
> 按照readme直接pnpm start:app:cr 启动，提示找不到命令。
> 
> 应该是mac terminal对--filter的解析未生效。
> 
> 建议将所有
> 
> ```
> "start:app:cr": "pnpm run start:cr --filter=@mometa/app",
> ```
> 
> 改为
> 
> ```
> "start:app:cr": "pnpm --filter=@mometa/app run start:cr",
> ```

我也遇到了这个问题，用了你的方法解决了，但是我有些不太懂当这个命令执行的时候，到底发生了啥。你能说下你的思路吗

**Comment by imcuttle** [comment]
fixed
