### ISSUE TITLE
Bug: app cannot run it.

### ISSUE THREAD

**Issue by Rain120** [imcuttle/mometa#7]

**Comment by imcuttle** [comment]
@Rain120  怎么复现该问题？

**Comment by Rain120** [comment]
## 复现环境

![image](https://user-images.githubusercontent.com/20939839/148324062-6dfe9011-25ba-4a18-b266-a106b78b3c51.png)

**Comment by Rain120** [comment]
## ReClone

### install 报错

![image](https://user-images.githubusercontent.com/20939839/148343074-373d1a6e-3149-4afa-8210-0db9a20d7705.png)

**Comment by imcuttle** [comment]
@Rain120  如果使用 npm@7，可以加上 --legacy-peer-deps 参数，或者切换为 npm@6 进行安装
